import "./globals.css";
import type { Metadata } from "next";
import React from "react";
import BookingForm from "@/components/forms/BookingForm";

export const metadata: Metadata = {
  title: "FlyDifferent",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="de">
      <body>
        <div>{children}</div>
      </body>
    </html>
  );
}
